services:
  ap:
    container_name: ap
    build: .
    privileged: true
    network_mode: none
    volumes:
      - ./volumes_ap:/volumes
    command: ["bash", "-c", "sleep infinity"]
    

  client:
    container_name: client
    build: .
    privileged: true
    network_mode: none
    volumes:
      - ./volumes_client:/volumes
    command: ["bash", "-c", "sleep infinity"]
    
  
  attacker:
    container_name: attacker
    build: .
    privileged: true
    network_mode: none
    volumes:
      - ./volumes_attacker:/volumes
    command: ["bash", "-c", "sleep infinity"]
  
  defender:
    container_name: defender
    build: .
    privileged: true
    network_mode: none
    volumes:
      - ./volumes_defender:/volumes
    command: ["bash", "-c", "sleep infinity"]
          

