services:
  ap:
    image: debian:stable
    privileged: true
    network_mode: none
    volumes:
      - volumes_ap:/volumes
    command: ["bash", "-c", "apt-get update && apt-get install -y hostapd iproute2 iputils-ping && hostapd /volumes/hostapd.conf"]

  client:
    image: debian:stable
    privileged: true
    network_mode: none
    volumes:
      - volumes_client:/volumes
    command: ["bash", "-c", "apt-get update && apt-get install -y wpasupplicant iproute2 iputils-ping && wpa_supplicant -Dnl80211 -iwlan1 -c /volumes/wpa_supplicant.conf -B"]
  
  attacker:
    image: debian:stable
    privileged: true
    network_mode: none
    volumes:
      - volumes_attacker:/volumes
    command: ["bash", "-c", "apt-get update && apt-get install -y wpasupplicant iproute2 iputils-ping && wpa_supplicant -Dnl80211 -iwlan1 -c /volumes/wpa_supplicant.conf -B"]
